# Copy this file to developer-config.yml
# You can simply remove settings that you don't need to override

# Names
vm_name: myproject
hostname: myproject

# Port forwarding
# Forward any additional ports or override the project ports
forward_ports:
  80: 9080
  443: 9443

# SSH Port
# If this is not specified then Vagrant will resolve it for you
ssh_port: 2222
