# Copy this file to developer-config.yml
# You can simply remove settings that you don't need to override

# Disable box update checks.  Slightly speeds up provisioning.
box_check_update: false

# Names
vm_name: myproject
hostname: myproject

# Port forwarding
# Forward any additional ports or override the project ports
forward_ports:
  80: 9080
  443: 9443

# SSH Port
# If this is not specified then Vagrant will resolve it for you
ssh_port: 2222

# Resources
ram: 2048
cpus: 1

# Bridged networking
# Use this to bridge the box as a peer on the local network
# Use the Virtualbox Manager to find the exact name of the adapter
bridged_adapter: "<name as shown in Virtualbox Manager>"
bridged_ip: "192.168.1.50"

# Run a shell script on boot
bootstrap: vagrant/developer.sh

# Docker compose file to up on boot.  Should be relative to Vagrantfile.
compose: ./dev-compose.yml

# Set this to true if your compose file overrides the project.  If this 
# is not set then both the project and dev compose files will be run.
compose_replace: false

# Disable key generation on vagrant up.  This allows you to use the
# default vagrant key every time.  Consider your network security first.
insecure_key: true

# Set a path for docker image caching.
# This greatly reduces vagrant destroy && vagrant up times.
docker_cache_path: C:\path\to\cache

# Specify id_rsa keys to copy to ~/.ssh
# Specify the private key.  The public key must be the same with a .pub extension
secret_rsa: secrets/id_rsa
