# Copy this file to developer-config.yml
# You can simply remove settings that you don't need to override

# Names
vm_name: myproject
hostname: myproject

# Port forwarding
# Forward any additional ports or override the project ports
forward_ports:
  80: 9080
  443: 9443

# SSH Port
# If this is not specified then Vagrant will resolve it for you
ssh_port: 2222

# Resources
ram: 2048
cpus: 1

# Bridged networking
# Use this to bridge the box as a peer on the local network
# Use the Virtualbox Manager to find the exact name of the adapter
bridged_adapter: "<name as shown in Virtualbox Manager>"
bridged_ip: "192.168.1.50"
