# This is a reference for project-config.yml
# You should version project-config.yml in your source control.

# Disable box update checks.  Slightly speeds up provisioning.
box_check_update: false

# Names
vm_name: myproject
hostname: myproject

# Ports that your project uses to forward to the host by default.
forward_ports:
  80: 8080
  443: 8443

# Run a shell script on boot
bootstrap: vagrant/project.sh

# Docker compose file to up on boot.  Should be relative to Vagrantfile.
compose: ./docker-compose.yml

# Specify tce extensions to install
# These are cached in vagrant/cache/tce for faster restarts.
# Note that the developer config can add to these so you should probably only
# install packages required by the project rather than developers, which makes the
# below a bad example.
tce_extensions:
  nano
  less
